num1 = int(input("Введите первое целое число: "))
num2 = int(input("Введите второе целое число: "))
num3 = int(input("Введите третье целое число: "))
num4 = int(input("Введите четвёртое целое число: "))
num5 = int(input("Введите пятое целое число: "))
maximum = max(num1, num2, num3, num4, num5)
print("Максимальное число:", maximum)
